spring.application.name=cryptowallet

spring.datasource.url=jdbc:postgresql://localhost:5432/cryptowallet
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

coincap.api.baseUrl=https://rest.coincap.io/v3
coincap.api.key=${COINCAP_API_KEY}

scheduler.price.cron=*/30 * * * * *
schedule.price.thread.pool.size=3